repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-json
    -   id: detect-private-key

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.55.0
    hooks:
    -   id: eslint
        files: \.(js|jsx)$
        types: [file]
        additional_dependencies:
        -   eslint@8.55.0
        -   eslint-config-standard@17.1.0
        -   eslint-plugin-import@2.29.0
        -   eslint-plugin-node@11.1.0
        -   eslint-plugin-promise@6.1.1

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
    -   id: prettier
        types_or: [javascript, jsx, json]
        additional_dependencies:
        -   prettier@3.1.0
